// <auto-generated />
using System;
using MediSync.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediSync.Migrations
{
    [DbContext(typeof(MediSyncContext))]
    partial class MediSyncContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MediSync.Models.Departamento", b =>
                {
                    b.Property<int>("Id_Departamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Departamento"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id_Departamento");

                    b.ToTable("Departamento");
                });

            modelBuilder.Entity("MediSync.Models.Expediente", b =>
                {
                    b.Property<int>("Id_Expediente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Expediente"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("Fecha_Ingreso")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("Hora_Ingreso")
                        .HasColumnType("time");

                    b.Property<int?>("Id_Departamento")
                        .HasColumnType("int");

                    b.Property<int?>("Id_Medico")
                        .HasColumnType("int");

                    b.Property<int>("Id_Paciente")
                        .HasColumnType("int");

                    b.Property<string>("Prediagnostico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sintomas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Expediente");

                    b.HasIndex("Id_Departamento");

                    b.HasIndex("Id_Medico");

                    b.HasIndex("Id_Paciente");

                    b.ToTable("Expediente");
                });

            modelBuilder.Entity("MediSync.Models.Medico", b =>
                {
                    b.Property<int>("Id_Medico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Medico"));

                    b.Property<string>("ContrasenaHash")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EsActivo")
                        .HasColumnType("bit");

                    b.Property<string>("Especialidad")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Id_Departamento")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id_Medico");

                    b.HasIndex("Id_Departamento");

                    b.ToTable("Medico");
                });

            modelBuilder.Entity("MediSync.Models.Paciente", b =>
                {
                    b.Property<int>("Id_Paciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Paciente"));

                    b.Property<string>("Contrasena")
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Contraseña");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Edad")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha_Registro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreContacto")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ParentescoContacto")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Sexo")
                        .HasColumnType("nvarchar(10)");

                    b.Property<long?>("Telefono")
                        .HasColumnType("bigint");

                    b.Property<long?>("TelefonoContacto")
                        .HasColumnType("bigint");

                    b.HasKey("Id_Paciente");

                    b.ToTable("Paciente");
                });

            modelBuilder.Entity("MediSync.Models.Expediente", b =>
                {
                    b.HasOne("MediSync.Models.Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("Id_Departamento");

                    b.HasOne("MediSync.Models.Medico", "Medico")
                        .WithMany()
                        .HasForeignKey("Id_Medico");

                    b.HasOne("MediSync.Models.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("Id_Paciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");

                    b.Navigation("Medico");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("MediSync.Models.Medico", b =>
                {
                    b.HasOne("MediSync.Models.Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("Id_Departamento");

                    b.Navigation("Departamento");
                });
#pragma warning restore 612, 618
        }
    }
}
